DROP TABLE IF EXISTS items CASCADE;

CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  -- order_id  INTEGER REFERENCES orders (id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL,
  description TEXT,
  img_url VARCHAR(255) NOT NULL,
  tag VARCHAR(255) NOT NULL,
  -- quantity 
);